##  Otto Group Product Kaggle Compittion 
- [ ] Create Custom Dataset


In [1]:
import numpy as np
import pandas as pd

In [164]:
kind = 'train'
data = pd.read_csv(f'./data/otto-group-product-classification-challenge/{kind}.csv', delimiter=',')
data.head()

id  feat_1  feat_2  feat_3  feat_4  feat_5  feat_6  feat_7  feat_8  feat_9  \
0   1       1       0       0       0       0       0       0       0       0   
1   2       0       0       0       0       0       0       0       1       0   
2   3       0       0       0       0       0       0       0       1       0   
3   4       1       0       0       1       6       1       5       0       0   
4   5       0       0       0       0       0       0       0       0       0   

   ...  feat_85  feat_86  feat_87  feat_88  feat_89  feat_90  feat_91  \
0  ...        1        0        0        0        0        0        0   
1  ...        0        0        0        0        0        0        0   
2  ...        0        0        0        0        0        0        0   
3  ...        0        1        2        0        0        0        0   
4  ...        1        0        0        0        0        1        0   

   feat_92  feat_93   target  
0        0        0  Class_1  
1        0        0  Class_1  
2        0        0  Class_1  
3        0        0  Class_1  
4        0        0  Class_1  

[5 rows x 95 columns]

In [130]:
data.isnull().sum()

id         0
feat_1     0
feat_2     0
feat_3     0
feat_4     0
          ..
feat_90    0
feat_91    0
feat_92    0
feat_93    0
target     0
Length: 95, dtype: int64

In [148]:
data.columns

Index(['id', 'feat_1', 'feat_2', 'feat_3', 'feat_4', 'feat_5', 'feat_6',
       'feat_7', 'feat_8', 'feat_9', 'feat_10', 'feat_11', 'feat_12',
       'feat_13', 'feat_14', 'feat_15', 'feat_16', 'feat_17', 'feat_18',
       'feat_19', 'feat_20', 'feat_21', 'feat_22', 'feat_23', 'feat_24',
       'feat_25', 'feat_26', 'feat_27', 'feat_28', 'feat_29', 'feat_30',
       'feat_31', 'feat_32', 'feat_33', 'feat_34', 'feat_35', 'feat_36',
       'feat_37', 'feat_38', 'feat_39', 'feat_40', 'feat_41', 'feat_42',
       'feat_43', 'feat_44', 'feat_45', 'feat_46', 'feat_47', 'feat_48',
       'feat_49', 'feat_50', 'feat_51', 'feat_52', 'feat_53', 'feat_54',
       'feat_55', 'feat_56', 'feat_57', 'feat_58', 'feat_59', 'feat_60',
       'feat_61', 'feat_62', 'feat_63', 'feat_64', 'feat_65', 'feat_66',
       'feat_67', 'feat_68', 'feat_69', 'feat_70', 'feat_71', 'feat_72',
       'feat_73', 'feat_74', 'feat_75', 'feat_76', 'feat_77', 'feat_78',
       'feat_79', 'feat_80', 'feat_81', 'feat_82', 'fe

In [147]:
import re
name = 'Class_3'
x = re.findall('\d+', name)
print(int(x[0]))

3


In [149]:
import re
def split_it(name):
    x = re.findall('\d+', name)
    return int(x[0])

In [150]:
split_it('class_2312x')

2312

In [151]:
data.target

0        Class_1
1        Class_1
2        Class_1
3        Class_1
4        Class_1
          ...   
61873    Class_9
61874    Class_9
61875    Class_9
61876    Class_9
61877    Class_9
Name: target, Length: 61878, dtype: object

In [152]:
data['target'] = data['target'].apply(split_it)

In [153]:
data.target

0        1
1        1
2        1
3        1
4        1
        ..
61873    9
61874    9
61875    9
61876    9
61877    9
Name: target, Length: 61878, dtype: int64

In [166]:
data['target'].apply(split_it).values()

TypeError: 'numpy.ndarray' object is not callable

In [122]:
import torch
from torch import nn, optim, tensor
from torch.utils.data import Dataset, DataLoader
import torch.nn.functional as F

In [167]:
import re
def split_it(name):
    x = re.findall('\d+', name)
    return int(x[0])

class OttoDatset(Dataset):
    def __init__(self):
        
        data = pd.read_csv(f'./data/otto-group-product-classification-challenge/train.csv', delimiter=',')
        data['target'] = data['target'].apply(split_it)
        self.len = data.shape[0]
        self.labels = tensor(data['target'].astype(np.float32).values)
        self.features = tensor(data.drop('target', axis=1).astype(np.float32).values)
        
    def __getitem__(self, index):
        return self.features[index], self.labels[index]
    
    def __len__(self):
        return self.len

In [168]:
otto = OttoDatset()

In [169]:
len(otto.features[0])

94

In [175]:
len(otto.labels)

61878

In [172]:
otto.labels[0]

tensor(1.)

In [104]:
otto.features[0]

tensor([ 1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
         0.,  0.,  0.,  2.,  0.,  0.,  0.,  0.,  1.,  0.,  4.,  1.,  1.,  0.,
         0.,  2.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,
         5.,  0.,  0.,  0.,  0.,  0.,  2.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
         0.,  2.,  0.,  0., 11.,  0.,  1.,  1.,  0.,  1.,  0.,  7.,  0.,  0.,
         0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  1.,  0.,  0.,  0.,
         0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [173]:
train_loader = DataLoader(otto,
                         batch_size=32,
                         shuffle=True)

In [189]:
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.fc1 = nn.Linear(94, 64)
        self.fc2 = nn.Linear(64, 32)
        self.fc3 = nn.Linear(32, 16)
        self.fc4 = nn.Linear(16, 9)
            
    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.relu(self.fc3(x))
        x = F.relu(self.fc4(x))
        return x

In [190]:
model = Model()
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.1, momentum=0.5)

In [191]:
w = 0

In [192]:
# Training loop
for epoch in range(2):
    for i, data in enumerate(train_loader, 0):
        # Get the data
        inputs, labels = data
        
        w = y_preds
        # Forward pass
        y_preds = model(inputs)
        
        # Loss
        loss = criterion(y_preds, labels)
        print(f"Epoch {epoch} | Batch: {i+1} | Loss: {loss.item():.4f}")
        
        # Zero grad, backward, upgrade
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

RuntimeError: Expected object of scalar type Long but got scalar type Float for argument #2 'target'

In [193]:
ss = nn.CrossEntropyLoss()

In [194]:
labels

tensor([2., 3., 9., 2., 2., 2., 4., 8., 1., 1., 8., 2., 5., 2., 3., 6., 6., 2.,
        7., 6., 2., 1., 8., 2., 1., 8., 8., 2., 6., 6., 8., 6.])

In [195]:
w

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]], grad_fn=<ReluBackward0>)

In [181]:
print(len(labels), len(w))

32 32


In [182]:
labels.type()

'torch.FloatTensor'

In [196]:
w

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]], grad_fn=<ReluBackward0>)

In [183]:
ss(w, labels)

RuntimeError: Expected object of scalar type Long but got scalar type Float for argument #2 'target'